### ISSUE TITLE
404 errors in Bit.Ly integration tests

### ISSUE THREAD

**Issue by julienc91** [MicroPyramid/microurl#18]
Two tests of `test_bitly_minify` are currently failing; `test_highvalue` and `test_search`.
Those two tests are respectively querying the following urls:

    https://api-ssl.bit.ly/v3/highvalue
    https://api-ssl.bit.ly/v3/search

But those two endpoints are returning a 404 error code, and are nowhere to be found in the [API documentation](http://dev.bitly.com/api.html).

**Comment by ashwin31** [comment]
it was due to depricated api end points, fixed now.
